# -*- coding: utf-8 -*-
"""learningEnglishFetch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-ZnT_W0rZqW8tAyEUc4_BewHxCJwCH3
"""

from requests_html import HTMLSession
import re
import time

session = HTMLSession()

def learningEnglishFetch(id):
    url = "http://m.xyybs.com/index.php?a=show&ewm=1&catid=152&id="+ str(id)
    h = session.get(url)
    titlesel = 'body > div.contentbox > h3'
    return h.html.find(titlesel)[0].text

learningEnglishFetch(26684) #test

titles = {}
links = {}
for id in range(29447,30086):
    titles[str(id)]= learningEnglishFetch(id)
    links[str(id)] = "http://m.xyybs.com/index.php?a=show&ewm=1&catid=152&id=" + str(id)

print(titles)

"""`id` 为文章编号；*dict* `output` 的值为标题。输出后只需找出含有 `高二江苏(N)` 的页面即可。"""